name: Pilie Speed Shop
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4848
title: Pilie Speed Shop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#73a7d9'
    - '#757470'
    - '#fefefe'
    - '#fe6077'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
